import type { Metadata } from 'next';
import Local from 'next/font/local';
import '@styles/globals.css';
import { links } from '@lib/links';
import { ReactNode } from 'react';
import Scripts from '@components/templates/scripts';

const cnFont = Local({
  src: './font_han_sans_cn_regular.otf',
  display: 'swap',
  variable: '--font-cn',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Scripts />
      </head>
      <body
        className={cnFont.className}
        style={{
          backgroundImage: `url('${links.background}')`,
          backgroundRepeat: 'no-repeat',
          backgroundSize: 'cover',
          backgroundAttachment: 'fixed',
        }}
      >
        {children}
      </body>
    </html>
  );
}
