name: CI

on:
  pull_request:
    branches: 
      - main

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Run linting
        run: npm run lint 
        