name: Linting

on:
  pull_request:
    branches: 
      - main

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Run linting
        run: npm run lint 
        
      - name: Commit changes
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "chore: Linting"
          git push
